
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://mopkxcpcmarwbnrqijya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vcGt4Y3BjbWFyd2JucnFpanlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MzE2NzMsImV4cCI6MjA2MDQwNzY3M30.DmVoegkjs72n3Xi0pheopWAUXtGs3TFHdK-LRTSIk_o";

// Define database types
export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          nome: string | null
          cargo: string | null
          departamento_id: string | null
          avatar_url: string | null
          nivel_acesso: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id: string
          nome?: string | null
          cargo?: string | null
          departamento_id?: string | null
          avatar_url?: string | null
          nivel_acesso?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          nome?: string | null
          cargo?: string | null
          departamento_id?: string | null
          avatar_url?: string | null
          nivel_acesso?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
      }
      departamentos: {
        Row: {
          id: string
          nome: string
          descricao: string | null
          cor: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          nome: string
          descricao?: string | null
          cor?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          nome?: string
          descricao?: string | null
          cor?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
      }
      tasks: {
        Row: {
          id: string
          title: string
          description: string | null
          status: string
          assignee_id: string | null
          due_date: string
          priority: string
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          title: string
          description?: string | null
          status?: string
          assignee_id?: string | null
          due_date?: string
          priority?: string
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          title?: string
          description?: string | null
          status?: string
          assignee_id?: string | null
          due_date?: string
          priority?: string
          created_at?: string | null
          updated_at?: string | null
        }
      }
      customers: {
        Row: {
          id: string
          name: string
          email: string | null
          phone: string | null
          status: string
          origem: string | null
          last_contact: string | null
          notes: string | null
          assigned_to: string | null
          value: number | null
          origem_options: string[] | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          name: string
          email?: string | null
          phone?: string | null
          status?: string
          origem?: string | null
          last_contact?: string | null
          notes?: string | null
          assigned_to?: string | null
          value?: number | null
          origem_options?: string[] | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          name?: string
          email?: string | null
          phone?: string | null
          status?: string
          origem?: string | null
          last_contact?: string | null
          notes?: string | null
          assigned_to?: string | null
          value?: number | null
          origem_options?: string[] | null
          created_at?: string | null
          updated_at?: string | null
        }
      }
    }
    Views: {
      team_by_department: {
        Row: {
          department_id: string | null
          department_name: string | null
          department_color: string | null
          member_count: number | null
          members: unknown[] | null
        }
      }
    }
    Functions: {
      get_user_nivel_acesso: {
        Args: { user_id: string }
        Returns: string
      }
      get_user_department: {
        Args: { user_id: string }
        Returns: string
      }
    }
    Enums: {
      // Define enums if needed
    }
  }
  storage: {
    Buckets: {
      avatars: {
        Row: {
          id: string
          name: string
          owner: string | null
          created_at: string | null
          updated_at: string | null
          public: boolean | null
          avif_autodetection: boolean | null
          file_size_limit: number | null
          allowed_mime_types: string[] | null
        }
      }
    }
    Objects: {
      [_ in string]: {
        Row: {
          name: string
          bucket_id: string
          owner: string | null
          created_at: string | null
          updated_at: string | null
          last_accessed_at: string | null
          metadata: Record<string, any> | null
        }
      }
    }
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
