// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mopkxcpcmarwbnrqijya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vcGt4Y3BjbWFyd2JucnFpanlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MzE2NzMsImV4cCI6MjA2MDQwNzY3M30.DmVoegkjs72n3Xi0pheopWAUXtGs3TFHdK-LRTSIk_o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);