// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dggkwnskloexmgrawooi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnZ2t3bnNrbG9leG1ncmF3b29pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NTQ1MjMsImV4cCI6MjA2MDIzMDUyM30._8vso9LVEhqDysRY7DLxmYxlrO_eHfrKNqEvZI5DZO0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);